#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 2):
	print "Usage: %s <ssid> [passphrase] [security]" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

print "Attempting to connect service %s" % (sys.argv[1])

if len(sys.argv) > 2:
	if len(sys.argv) > 3:
		security = sys.argv[3]
	else:
		security = "rsn"
	passphrase = sys.argv[2]
else:
	security = "none"
	passphrase = ""

path = manager.ConnectService(({ "Type": "wifi", "Mode": "managed",
					"SSID": sys.argv[1],
					"Security": security,
					"Passphrase": passphrase }));
print "Service path is %s" %(path)
