#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 2):
	print "Usage: %s type" % (sys.argv[0])

print "Disabling %s tethering" % (sys.argv[1])

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('net.connman', "/"),
					'net.connman.Manager')

def technology_disable_tethering(path, tech_type):
	tech = dbus.Interface(bus.get_object("net.connman", path),
						"net.connman.Technology")

	properties = tech.GetProperties()

	for key in properties.keys():
		if key in ["Type"]:
			if properties[key] == tech_type:
				tech.SetProperty("Tethering", dbus.Boolean(0))

properties = manager.GetProperties()

for key in properties.keys():
	if key in ["Technologies"]:
		for path in properties[key]:
			technology_disable_tethering(path, sys.argv[1])
