#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.moblin.connman', "/"),
					'org.moblin.connman.Manager')

properties = manager.GetProperties()

for path in properties["Devices"]:
	device = dbus.Interface(bus.get_object('org.moblin.connman', path),
						'org.moblin.connman.Device')

	properties = device.GetProperties()

	if (properties["Powered"] == dbus.Boolean(0)):
		continue

	print "[ %s ]" % (path)

	device.SetProperty("Powered", dbus.Boolean(0));
