#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 2):
	print "Usage: %s <device>" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.moblin.connman', "/"),
					'org.moblin.connman.Manager')

properties = manager.GetProperties()

for path in properties["Devices"]:
	device = dbus.Interface(bus.get_object('org.moblin.connman', path),
						'org.moblin.connman.Device')

	properties = device.GetProperties()

	if properties["Interface"] != sys.argv[1]:
		continue;

	print "Disabling device %s" % (path)

	device.SetProperty("Powered", dbus.Boolean(0));
