#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.moblin.connman', "/"),
					'org.moblin.connman.Manager')

properties = manager.GetProperties()

print "System is %s" % (properties["State"])
