#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.freedesktop.connman', "/"),
					'org.freedesktop.connman.Manager')

interfaces = manager.ListInterfaces()

for path in interfaces:
	print "[ %s ]" % (path)

	interface = dbus.Interface(bus.get_object('org.freedesktop.connman', path),
					'org.freedesktop.connman.Interface')

	properties = interface.GetProperties()
	for key in properties.keys():
		print "    %s = %s" % (key, properties[key])

	ipv4 = interface.GetIPv4()
	for key in ipv4.keys():
		print "    IPv4.%s = %s" % (key, ipv4[key])

	print
