#!/usr/bin/python

import dbus

def extract_values(values):
	val = "{"
	for key in values.keys():
		val += " " + key + "="
		val += str(values[key])
	val += " }"
	return val

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

properties = manager.GetProperties()

for path in properties["Services"]:
	service = dbus.Interface(bus.get_object("org.moblin.connman", path),
						"org.moblin.connman.Service")

	properties = service.GetProperties()

	print "[ %s ]" % (path)

	for key in properties.keys():
		if key in ["IPv4", "IPv4.Configuration", "Ethernet"]:
			val = extract_values(properties[key])
		elif key in ["Favorite", "AutoConnect",
				"SetupRequired", "PassphraseRequired"]:
			if properties[key] == dbus.Boolean(1):
				val = "true"
			else:
				val = "false"
		elif key in ["Strength"]:
			val = int(properties[key])
		else:
			val = str(properties[key])
		print "    %s = %s" % (key, val)

	print
