#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("net.connman", "/"),
					"net.connman.Manager")

properties = manager.GetProperties()

active = properties["ActiveProfile"]

for path in properties["Profiles"]:
	if (active == path):
		print "[ %s ]  <== active" % (path)
	else:
		print "[ %s ]" % (path)

	profile = dbus.Interface(bus.get_object("net.connman", path),
						"net.connman.Profile")

	properties = profile.GetProperties()
	for key in properties.keys():
		if key in ["Services"]:
			list = ""
			for path in properties["Services"]:
				val = str(path)
				list = list + val[val.rfind("/") + 1:] + " "
			print "    Services = [ %s]" % (list)
		else:
			print "    %s = %s" % (key, properties[key])

	print
