#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

properties = manager.GetProperties()

for path in properties["Profiles"]:
	print "[ %s ]" % (path)

	element = dbus.Interface(bus.get_object("org.moblin.connman", path),
						"org.moblin.connman.Profile")

	properties = element.GetProperties()
	for key in properties.keys():
		print "    %s = %s" % (key, properties[key])

	print
