#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.moblin.connman', "/"),
					'org.moblin.connman.Manager')

interfaces = manager.ListInterfaces()

for path in interfaces:
	print "[ %s ]" % (path)

	interface = dbus.Interface(bus.get_object('org.moblin.connman', path),
					'org.moblin.connman.Interface')

	properties = interface.GetProperties()
	for key in properties.keys():
		print "    %s = %s" % (key, properties[key])

	ipv4 = interface.GetIPv4()
	for key in ipv4.keys():
		print "    IPv4.%s = %s" % (key, ipv4[key])

	networks = interface.ListNetworks()
	for i in networks:
		print "    Network.Path = %s" % (i)

		network = dbus.Interface(bus.get_object('org.moblin.connman', i),
						'org.moblin.connman.Network')

		print "    Network.Identifier = %s" % (network.GetIdentifier())
		print "    Network.Passphrase = %s" % (network.GetPassphrase())

	print
