#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

properties = manager.GetProperties()

for path in properties["Connections"]:
	connection = dbus.Interface(bus.get_object("org.moblin.connman", path),
						"org.moblin.connman.Connection")

	properties = connection.GetProperties()

	print "[ %s ]" % (path)

	for key in properties.keys():
		print "    %s = %s" % (key, properties[key])

	print
