#!/usr/bin/python

import gobject

import dbus
import dbus.mainloop.glib

def property_changed(name, value):
	if name in ["Profiles", "Services", "Technologies"]:
		val = "["
		for i in value:
			val = val + " " + i[i.rfind("/") + 1:]
		val = val + " ]"
	elif name in ["AvailableTechnologies", "EnabledTechnologies",
						"ConnectedTechnologies",
				"AvailableDebugs", "EnabledDebugs"]:
		val = "["
		for i in value:
			val = val + " " + i
		val = val + " ]"
	elif name in ["Strength", "Priority"]:
		val = int(value)
	else:
		val = str(value)
	print "%s = %s" % (name, val)

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

	bus = dbus.SystemBus()

	bus.add_signal_receiver(property_changed,
				bus_name="net.connman",
				dbus_interface="net.connman.Manager",
					signal_name = "PropertyChanged")

	mainloop = gobject.MainLoop()
	mainloop.run()
