#!/usr/bin/python

import gobject

import dbus
import dbus.mainloop.glib

def extract_values(values):
	val = "{"
	for key in values.keys():
		val += " " + key + "="
		val += str(values[key])
	val += " }"
	return val

def property_changed(name, value, path):
	service = path[path.rfind("/") + 1:]
	if name in ["Profiles", "Services", "Providers", "Technologies",
						"Devices", "Networks"]:
		val = "["
		for i in value:
			val = val + " " + i[i.rfind("/") + 1:]
		val = val + " ]"
	elif name in ["IPv4", "IPv4.Configuration", "Proxy", "Ethernet"]:
		val = extract_values(value)
	elif name in ["Strength", "Priority"]:
		val = int(value)
	else:
		val = str(value)
	print "[%s] %s = %s" % (service, name, val)

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

	bus = dbus.SystemBus()

	bus.add_signal_receiver(property_changed,
				bus_name="org.moblin.connman",
				dbus_interface="org.moblin.connman.Service",
				signal_name = "PropertyChanged",
				path_keyword="path")

	mainloop = gobject.MainLoop()
	mainloop.run()
