#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 2):
	print "Usage: %s <network>" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

elements = manager.ListElements()

for path in elements:
	element = dbus.Interface(bus.get_object("org.moblin.connman", path),
						"org.moblin.connman.Element")

	properties = element.GetProperties()
	if (properties["Type"] != "network"):
		continue

	if (properties["Enabled"] == dbus.Boolean(1)):
		continue

	if (properties["WiFi.Name"] == sys.argv[1]):
		print "Enabling %s" % (path)
		element.Enable()
