#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

properties = manager.GetProperties()

for path in properties["Connections"]:
	connection = dbus.Interface(bus.get_object("org.moblin.connman", path),
						"org.moblin.connman.Connection")

	properties = connection.GetProperties()

	if (properties["Default"] == dbus.Boolean(1)):
		continue

	print "[ %s ]" % (path)

	connection.SetProperty("Default", dbus.Boolean(1))
