#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.freedesktop.connman', "/"),
					'org.freedesktop.connman.Manager')

interfaces = manager.ListInterfaces()

for path in interfaces:
	print "[ %s ]" % (path)

	interface = dbus.Interface(bus.get_object('org.freedesktop.connman', path),
					'org.freedesktop.connman.Interface')

	properties = interface.GetProperties()

	if (properties["Type"] == "80211"):
		networks = interface.ListNetworks()
		for i in networks:
			network = dbus.Interface(bus.get_object('org.freedesktop.connman', i),
						'org.freedesktop.connman.Network')

			if (network.GetIdentifier() == "ConnMan Testing"):
				print "   Selecting network %s" % (i)
				interface.SelectNetwork(i)
	else:
		print "   No networks"

	print
