#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 3):
	print "Usage: %s <address> <netmask | prefix length> <gateway> [version]" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.moblin.connman', "/"),
					'org.moblin.connman.Manager')

properties = manager.GetProperties()

for path in properties["Services"]:
	service = dbus.Interface(bus.get_object('org.moblin.connman', path),
						'org.moblin.connman.Service')

	properties = service.GetProperties()



	if (len(sys.argv) == 5 and sys.argv[4] == "ipv6"):
		ipv = 6
	else:
		ipv = 4

	print "Setting IPv%d address %s for %s" % (ipv, sys.argv[1], path)

	if (ipv == 4):
		service.SetProperty("IPv4.Configuration",
					{ "Method": "manual",
						"Address": sys.argv[1],
						"Netmask": sys.argv[2],
							"Gateway": sys.argv[3]})
	else:
		service.SetProperty("IPv6.Configuration",
					{ "Method": "manual",
						"Address": sys.argv[1],
						"PrefixLength": sys.argv[2],
							"Gateway": sys.argv[3]})

	print
