#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 3):
	print "Usage: %s <address> <netmask> <gateway>" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.moblin.connman', "/"),
					'org.moblin.connman.Manager')

properties = manager.GetProperties()

for path in properties["Services"]:
	service = dbus.Interface(bus.get_object('org.moblin.connman', path),
						'org.moblin.connman.Service')

	properties = service.GetProperties()

	print "Setting address %s for %s" % (sys.argv[1], path)

	service.SetProperty("IPv4.Configuration",
		{ "Method": "manual", "Address": sys.argv[1],
			"Netmask": sys.argv[2], "Gateway": sys.argv[3]})

	print
