#!/usr/bin/python

import sys
import dbus

def print_usage():
	print "Usage: %s <service> [off|dhcp|manual <address> [netmask] [gateway]]" % (sys.argv[0])


if (len(sys.argv) < 3):
	print_usage()
	sys.exit(1)

bus = dbus.SystemBus()
path = "/net/connman/service/" + sys.argv[1]
service = dbus.Interface(bus.get_object('net.connman', path),
					'net.connman.Service')

properties = service.GetProperties()

print "Setting method %s for %s" % (sys.argv[2], sys.argv[1])

ipv4_configuration = { "Method": sys.argv[2] }
if (len(sys.argv) > 3):
	ipv4_configuration["Address"] = sys.argv[3]
if (len(sys.argv) > 4):
	ipv4_configuration["Netmask"] = sys.argv[4]
if (len(sys.argv) > 5):
        ipv4_configuration["Gateway"] = sys.argv[5]

service.SetProperty("IPv4.Configuration", ipv4_configuration)
print "New IPv4.Configuration: ", ipv4_configuration

print
