#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

object = dbus.Interface(bus.get_object("org.moblin.connman", '/'),
				"org.freedesktop.DBus.Introspectable")

print object.Introspect()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

elements = manager.ListElements()

for path in elements:
	object = dbus.Interface(bus.get_object("org.moblin.connman", path),
					"org.freedesktop.DBus.Introspectable")

	print object.Introspect()
