#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.moblin.connman', "/"),
					'org.moblin.connman.Manager')

properties = manager.GetProperties()

for path in properties["Technologies"]:
	technology = dbus.Interface(bus.get_object('org.moblin.connman', path),
						'org.moblin.connman.Technology')
	properties = technology.GetProperties()

	print "[ %s ]" % (path)

	if properties["Type"] in ["wifi", "wimax"]:

		print "   Started scanning"

		for path in properties["Devices"]:
			device = dbus.Interface(bus.get_object('org.moblin.connman', path),
								'org.moblin.connman.Device')
			try:
				device.ProposeScan()
			except dbus.DBusException, error:
				print "   %s: %s" % (error._dbus_error_name, error.message)
	else:
		print "   No scanning"

	print
