#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.freedesktop.NetworkManager',
				'/org/freedesktop/NetworkManager'),
					'org.freedesktop.NetworkManager')

state = manager.state()

print "System is %d" % (state)
