#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.moblin.connman", "/"),
					"org.moblin.connman.Manager")

properties = manager.GetProperties()

def print_properties(key, value):
	if key == "Profiles":
		interface = "org.moblin.connman.Profile"
	elif key == "Devices":
		interface = "org.moblin.connman.Device"
	elif key == "Connections":
		interface = "org.moblin.connman.Connection"
	else:
		return

	print "%s" % (key)
	for path in value:
		print "    %s" % (path)
		obj = dbus.Interface(bus.get_object("org.moblin.connman", path),
								interface)

		properties = obj.GetProperties()

		for key in properties.keys():
			if key == "Networks":
				continue

			if key in ["Powered", "Scanning", "Connected",
					"Available", "Remember", "Default"]:
				if properties[key] == dbus.Boolean(1):
					val = "true"
				else:
					val = "false"
			elif key == "Strength":
				val = int(properties[key])
			else:
				val = str(properties[key])

			print "        %s = %s" % (key, val)

		if "Networks" in properties.keys():
			list = ""
			for path in properties["Networks"]:
				val = str(path)
				list = list + val[val.rfind("/") + 1:] + " "
			print "        Networks = [ %s]" % (list)

for key in properties.keys():
	if key in ["Profiles", "Devices", "Connections"]:
		print_properties(key, properties[key])
	else:
		print "%s" % (key)
		print "    %s" % (properties[key])
